# -*- coding: utf-8 -*-
"""python_basics_<kaira_sudhiksha>.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oLQiVMwu_GrbmfKWLuLfzLLXiG1BSRZA
"""

name = "shiva"
age = 26
height = 5.4
is_student = True
print(name, age, height, is_student)
print(f"Name: {name} | Age: {age} | Height: {height} | Student: {is_student}")
age_in_months = age*12
age_in_days = age*365
remainder_by_7 = age%7
age_squared = age**2
print(f"Age in months: {age_in_months}")
print(f"Age in days: {age_in_days}")
print(f"Remainder when age is divided by 7: {remainder_by_7}")
print(f"Age raised to the power of 2: {age_squared}")

